# Generated by Django 4.2.1 on 2023-06-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('descricao', models.TextField()),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
    ]
