# Generated by Django 4.2.1 on 2023-06-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_rename_quantidade_item_quantidade_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigo_item',
            field=models.CharField(default=1, max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
