# Generated by Django 4.2.1 on 2023-06-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_item_codigo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
