# Generated by Django 4.2.1 on 2023-06-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(default='YC46MIKO', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itenspedido', to='pedidos.pedido'),
        ),
    ]
